#!/bin/sh

#pull *.mk:tests/* from david@localhost
#push Makefile to user@host

ROOT=~/.mtrn
REMOTES=$ROOT/remotes

RSYNC="echo $(which rsync)"
SSH=$(which ssh)
SSH_DEFAULT_PORT=$(sed -nr 's|^.*ssh[\t ]+([0-9]+)/tcp.*$|\1|p' /etc/services) #'

exec 3<$REMOTES
while read -u 3 CMD1 SOURCE CMD2 TARGET; do
    case "${CMD1}${CMD2}" in
	pullfrom)
	    echo $TARGET | sed 's/:/ /' | read TARGET SSH_PORT
	    if [ "X$PORT" = "X" ]; then
		SSH_PORT=$SSH_DEFAULT_PORT
	    fi
	    for FILE in $(echo $SOURCE | sed 's/:/ /g'); do
		$RSYNC -vrRte "$SSH -p $SSH_PORT" $FILE $TARGET
	    done
	;;
	pushto)
	    echo $SOURCE | sed 's/:/ /' | read SOURCE SSH_PORT
	    if [ "X$PORT" = "X" ]; then
		SSH_PORT=$SSH_DEFAULT_PORT
	    fi
	    for FILE in $(echo $TARGET | sed 's/:/ /g'); do
		$RSYNC -vrRte "$SSH -p $SSH_PORT" $FILE $SOURCE
	    done
	;;
	*)
	    echo "wrong line: $* $@"
	;;
    esac
done
